// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABARFErR1uBUP0zoYPFIbF_Z_3c12GQZA',
    appId: '1:1086281241029:android:42166db2515ee710c77bac',
    messagingSenderId: '1086281241029',
    projectId: 'tdpapp-8d28b',
    storageBucket: 'tdpapp-8d28b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2lZXUoI39SpIYLxwe0J5h1V9dGmI64Kw',
    appId: '1:1086281241029:ios:457352b06c766f8cc77bac',
    messagingSenderId: '1086281241029',
    projectId: 'tdpapp-8d28b',
    storageBucket: 'tdpapp-8d28b.appspot.com',
    iosClientId: '1086281241029-59rkvc280j8na1gb1q6kon46rjjpqok7.apps.googleusercontent.com',
    iosBundleId: 'com.example.tdpapp',
  );
}
